# 修改配置 请查看 .env 文件以及app目录, 次文件尽量不要修改
version: '3.1'
services:
  nginx:
    restart: always
    image: nginx:1.23.3
    container_name: ${container_app_name}-${container_front_end_subname}
    ports:
      - ${front_end_port}:${container_front_end_port}
    volumes:
      - ./data/nginx/conf.d/:/etc/nginx/conf.d
      - ./app/html:/usr/share/nginx/html
      - ./data/nginx/logs:/var/log/nginx
      - ./data/init/nginx.conf:/etc/nginx/nginx.conf:ro
  backend:
    restart: always
    build:
      context: ./app
      dockerfile: dockerfile
    image: ${container_app_name}-${container_backend_subname}:1.0
    container_name: ${container_app_name}-${container_backend_subname}
    ports:
      - ${backend_port}:${container_backend_port}
    volumes:
      - ./data/backend:/app/data
    environment:
      mysql_password: ${mysql_password}
      container_mysql_port: ${container_mysql_port}
      mysql_init_database_name: ${mysql_init_database_name}
      redis_password: ${redis_password}
  mysql:
    image: mysql:8.0
    container_name: ${container_app_name}-${container_mysql_subname}
    restart: always
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
      - --init-connect='SET NAMES utf8mb4'
      - --init-connect='SET collation_connection = utf8_unicode_ci'
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_password}
      MYSQL_DATABASE: ${mysql_init_database_name}
      TZ: Asia/Shanghai
      LANG: "en_US.UTF-8"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./app:/docker-entrypoint-initdb.d # 初始化脚本目录
    ports:
      - ${mysql_port}:${container_mysql_port} 
  redis:
    image: redis:5
    restart: always
    container_name: ${container_app_name}-${container_redis_subname}
    command:
      - /bin/bash
      - -c
      - redis-server /usr/local/bin/redis.conf/redis.conf --requirepass ${redis_password}
    privileged: true
    volumes:
      - ./data/redis/data:/data
      - ./data/redis/redis.conf:/usr/local/bin/redis.conf/redis.conf
    ports:
      - ${redis_port}:${container_redis_port}
# 配置网络, 配置了这个之后在容器内部可以直接使用服务名来当作域名访问
networks:
  default: